SELECT
    'INSERT INTO PROIBICAO (CD_PRO_FAT, CD_CON_PLA, CD_CONVENIO, DS_PROIBICAO, TP_PROIBICAO, TP_ATENDIMENTO, DT_INICIAL_PROIBICAO, CD_MULTI_EMPRESA, CD_SETOR, CD_REGRA_PROIBICAO_VALOR, DT_FIM_PROIBICAO) VALUES ('''
    || PRO_FAT.CD_PRO_FAT || ''', ' || CON_PLA.CD_CON_PLA || ', ' || CONVENIO.CD_CONVENIO || ', NULL, ''NA'', '|| PORTA.DS_PORTA || ', ''21/11/2023'', 1, NULL, NULL, NULL);' INSERCAO
FROM
    PRO_FAT, 
    (SELECT 'A' DS_PORTA FROM DUAL
    UNION ALL
    SELECT 'E' FROM DUAL
    UNION ALL
    SELECT 'I' FROM DUAL
    UNION ALL
    SELECT 'U' FROM DUAL) PORTA,
    CONVENIO,
    CON_PLA 
WHERE
    CONVENIO.CD_CONVENIO = CON_PLA.CD_CONVENIO;